name: API CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    env:
      CI: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: | 
        npm ci
        npm test
        
    - name: Cache
      uses: actions/cache@v2.1.1
      with:
        path: 
          ./node_modules 
          ./package*.json
          ~/.npm 
        key:  ${{ matrix.node-version }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ matrix.node-version }}-node-${{ hashFiles('**/package.json') }}
